#!/usr/bin/env python3
"""Generate GitHub Pages content from CI artifacts."""

import html
import json
import os
import shutil

ARTIFACT_DIR = os.environ.get("ARTIFACT_DIR", "artifacts")
OUT_DIR = os.environ.get("OUT_DIR", "public")


def read_file(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip()
    except FileNotFoundError:
        return None


def copy_coverage():
    src = os.path.join(ARTIFACT_DIR, "coverage", "coverage_html")
    dst = os.path.join(OUT_DIR, "coverage")
    if os.path.isdir(src):
        shutil.copytree(src, dst)
        return True
    return False


def get_coverage_pct():
    pct = read_file(os.path.join(ARTIFACT_DIR, "coverage", "coverage_pct.txt"))
    if pct:
        try:
            return float(pct)
        except ValueError:
            pass
    return None


def coverage_color(pct):
    if pct is None:
        return "lightgrey"
    if pct >= 90:
        return "brightgreen"
    if pct >= 75:
        return "green"
    if pct >= 60:
        return "yellow"
    return "red"


def write_badge_json(pct):
    badge_dir = os.path.join(OUT_DIR, "badges")
    os.makedirs(badge_dir, exist_ok=True)
    label = f"{pct:.1f}%" if pct is not None else "N/A"
    badge = {
        "schemaVersion": 1,
        "label": "coverage",
        "message": label,
        "color": coverage_color(pct),
    }
    with open(os.path.join(badge_dir, "coverage.json"), "w") as f:
        json.dump(badge, f)


def generate_index(has_coverage, coverage_pct):
    cov_section = ""
    if has_coverage:
        pct_str = html.escape(f"{coverage_pct:.1f}%" if coverage_pct else "N/A")
        cov_section = f"""
    <div class="card">
      <h2>Code Coverage</h2>
      <p class="metric">{pct_str}</p>
      <a href="coverage/">Full Report &rarr;</a>
    </div>"""

    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Vortex Dashboard</title>
  <style>
    :root {{ --bg: #0d1117; --fg: #c9d1d9; --card: #161b22; --accent: #58a6ff; }}
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif;
           background: var(--bg); color: var(--fg); padding: 2rem; }}
    h1 {{ color: var(--accent); margin-bottom: 1.5rem; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; }}
    .card {{ background: var(--card); border-radius: 8px; padding: 1.5rem; }}
    .card h2 {{ color: var(--accent); margin-bottom: 0.5rem; font-size: 1.1rem; }}
    .card a {{ color: var(--accent); text-decoration: none; }}
    .card a:hover {{ text-decoration: underline; }}
    .metric {{ font-size: 2rem; font-weight: bold; margin: 0.5rem 0; }}
    footer {{ margin-top: 2rem; color: #484f58; font-size: 0.85rem; }}
  </style>
</head>
<body>
  <h1>Vortex Dashboard</h1>
  <div class="grid">
{cov_section}
  </div>
  <footer>Auto-generated by CI</footer>
</body>
</html>"""
    with open(os.path.join(OUT_DIR, "index.html"), "w") as f:
        f.write(index_html)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    has_coverage = copy_coverage()
    coverage_pct = get_coverage_pct()

    write_badge_json(coverage_pct)
    generate_index(has_coverage, coverage_pct)

    print(f"Pages content generated in {OUT_DIR}/")
    if coverage_pct is not None:
        print(f"  Coverage: {coverage_pct:.1f}%")


if __name__ == "__main__":
    main()
